### ISSUE TITLE
Consider negating the spec's conditional?

### ISSUE THREAD

**Issue by domenic** [unpkg/babel-plugin-unpkg-rewrite#1]
It looks like currently this augments specifiers which do not contain `.` or `/`

I think instead it might be better to augment things that per-spec always throw a TypeError. That is, augment things that do not start with `./`, `../` or `/`.

This probably doesn't matter much in practice, but e.g. it would allow `import 'lodash.somemethod'` to get rewritten, whereas I believe the current algorithm does not allow that. Similarly, I'm not sure if unpkg supports submodules, but my algorithm would allow `import 'pn/fs'`, whereas the current algorithm does not.

**Comment by domenic** [comment]
Oh, I guess I forgot the most important conditional: things that parse as a URL. So you'd also have to do a URL parse and if that succeeds, don't rewrite.

Maybe that's too heavyweight. But if it's not, I recommend jsdom/whatwg-url for all your URL-parsing needs.

**Comment by threepointone** [comment]
the conditional checks for first character, so it should be fine? Good point about URLs, added that. I'll substitute `whatwg-url` with something lighter if the need arises, but it seems fine for now. 

@domenic - the [readme](https://github.com/threepointone/babel-plugin-import-bare/blob/master/README.md) has input/output examples, would you please have a quick look and tell me if that's alright? any other cases I missed?

**Comment by domenic** [comment]
Oh I see I misread the code!

The other case is that it should in theory rewrite `.foo` or `..foo`. It's only `./foo` and `../foo` that are going to get loaded in a browser. I doubt that matters given the constraints of npm/unpkg though.

The readme examples look good. If you really want to be thorough you might want to consult the example at https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

**Comment by threepointone** [comment]
Neat, thank you! I'll incorporate them all.

**Comment by hemanth** [comment]
Looks like `bypass actual urls` is done, only the optional TODO is left.

**Comment by threepointone** [comment]
As well as, y'know, making it actually work with unpkg 😂

**Comment by hemanth** [comment]
![](https://media.tenor.co/images/f9cf63d5bbeb6d7f7c14b30dbce2b46a/raw)
