### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by mjackson** [unpkg/babel-plugin-unpkg-rewrite#4]
Can we just hook it up to `npm test`?

**Comment by hemanth** [comment]
🌵 Totally forgot about this! 

I shall update ASAP.

**Comment by hemanth** [comment]
@mjackson With [67eee](https://github.com/unpkg/babel-plugin-unpkg-rewrite/commit/1df4f160f1d8cb2c52320aa4d0275c42c6167eee) `npm test` must work.
